module.exports = function ({
  name,
  username,
  email,
  mobilePhone = "+91",
  password
}) {
  return {
    "userName": username,
    "primaryRole": "ManagerReadOnly",
    "name": name,
    "enterpriseRole": null,
    "enterpriseRoleId": null,
    "department": null,
    "departmentId": null,
    "reportsTo": null,
    "languages": null,
    "regions": null,
    "email": email,
    "mobilePhone": mobilePhone,
    "locationFilter": null,
    "conditionalFilter": {
      "location": [],
      "surveyClient": [],
      "afterdate": null,
      "beforedate": null,
      "filterquestions": [],
      "archived": false,
      "channel": null,
      "withTickets": false,
      "withTicketStatus": null,
      "withNotes": false,
      "notesWithAttachmentType": null,
      "notesMediaTheme": null,
      "notesMediaMood": null,
      "onlyWithAttachments": false,
      "days": [],
      "aftertime": null,
      "beforetime": null,
      "ticket": null,
      "filterName": null,
      "withArchived": false,
      "onlyOutliers": false
    },
    "myViews": null,
    "password": password,
    "isEmailVerified": true,
    "isMobilePhoneVerified": false,
    "promptPasswordChange": false,
    "exemptSSOLock": false,
    "timeZoneOffset": 0,
    "highPrecisionMode": false,
    "alwaysEnforceTwoFactor": false,
    "restrictPIIData": false,
    "allowRestrictedDataUntil": null
  }
}