module.exports = function ({
  name,
  username,
  email,
  mobilePhone = '+91',
  password,
  enterpriseRole = 'Contact Center - Agent',
  enterpriseRoleId = '5e9964534e67f10e4873af46',
  department = 'Contact Center',
  departmentId = '5e9964764e67f10e4873af47'
}) {
  return {
    'userName': username,
    'primaryRole': 'ManagerReadOnly',
    'name': name,
    enterpriseRole,
    enterpriseRoleId,
    department,
    departmentId,
    'reportsTo': null,
    'languages': null,
    'regions': null,
    email,
    mobilePhone,
    'locationFilter': null,
    'conditionalFilter': {
      'location': [],
      'surveyClient': [],
      'afterdate': null,
      'beforedate': null,
      'filterquestions': [],
      'archived': false,
      'channel': null,
      'withTickets': false,
      'withTicketStatus': null,
      'withNotes': false,
      'notesWithAttachmentType': null,
      'notesMediaTheme': null,
      'notesMediaMood': null,
      'onlyWithAttachments': false,
      'days': [],
      'aftertime': null,
      'beforetime': null,
      'ticket': null,
      'filterName': null,
      'withArchived': false,
      'onlyOutliers': false
    },
    'myViews': null,
    password,
    'isEmailVerified': true,
    'isMobilePhoneVerified': false,
    'promptPasswordChange': false,
    'exemptSSOLock': false,
    'timeZoneOffset': 0,
    'highPrecisionMode': false,
    'alwaysEnforceTwoFactor': false,
    'restrictPIIData': false,
    'allowRestrictedDataUntil': null
  }
}